/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
export async function seed(knex) {
  // Deletes ALL existing entries
  await knex('artwork').del()
  await knex('artwork').insert([
    {
      "id": 106237,
      "title": "Dagger with Two Awls and Sheath for the Bodyguard of the Elector of Saxony",
      "date_start": 1575,
      "date_end": 1585,
      "artist_display": "Silver mounts marked by Wolf Paller Paller (German, died 1583)\nDresden",
      "place_of_origin": "Dresden",
      "description": null,
      "dimensions": "H.: 36.8 cm (14 1/2 in.); Blade: H.: 26 cm (10 1/4 in.); Scabbard: H.: 29.2 cm (11 1/2 in.)",
      "medium_display": "Steel, silver, wood, and leather",
      "credit_line": "George F. Harding Collection",
      "provenance_text": null,
      "artwork_type_title": "Arms",
      "artist_id": 66563,
      "artist_title": "Wolf Paller",
      "term_titles": "[\"edged weapon-dagger\",\"arms\",\"arms and armor\"]",
      "image_id": "aad9ef5d-5d5b-1ab9-fd89-d44677de5c7b",
      "alt_text": "A work made of steel, silver, wood, and leather."
    },
    {
      "id": 106431,
      "title": "Triple-Wheellock Pistol",
      "date_start": 1610,
      "date_end": 1620,
      "artist_display": "Franco-German (Alsatian); Strasbourg",
      "place_of_origin": "Strasbourg",
      "description": "<p>The half minute needed to wind and load a wheellock pistol led to the invention of various multilock and multibarrel systems. Here three independent pistols are stocked together with alternating triggers.</p>\n<p>To fire the weapon, the shooter need only rotate the grip on the gun and pull the next trigger.</p>\n",
      "dimensions": "Overall L. 72 cm (28 3/4 in.) \nBarrel L. 49 cm (19 5/16 in.)\nWt. 5 lb. 4 oz.\nCaliber .35",
      "medium_display": "Steel, brass, and cherrywood",
      "credit_line": "George F. Harding Collection",
      "provenance_text": null,
      "artwork_type_title": "Arms",
      "artist_id": 80651,
      "artist_title": "Wolf Jung",
      "term_titles": "[\"firearm-handgun\",\"arms\",\"arms and armor\"]",
      "image_id": "a70b104d-50a2-2563-f7f8-bc21ce7679f0",
      "alt_text": "A work made of steel, brass, and cherrywood."
    },
    {
      "id": 6792,
      "title": "A Falconer with Two Ladies and a Foot Soldier",
      "date_start": 1490,
      "date_end": 1510,
      "artist_display": "Franco-Flemh, possibly Paris or Bruges",
      "place_of_origin": "Bruges",
      "description": "<p>Two fashionably dressed women, a man in falconer’s garb, another man in the less ornate costume of a foot soldier, and a dog occupy an island surrounded by a flat expanse covered in an overall pattern of small flowers and plants known as millefleur. The shallow, earthy cross section visible on the front edge of the island reveals that some attempt was made to create an impression of depth. It is unlikely that this image had any particular symbolic or narrative significance; rather, it was probably the decorative qualities of the figures’ stances and costumes and the fantastical millefleur setting that appealed to contemporary viewers. Such millefleur designs were extremely popular because of their accessibility, functional flexibility, and manageable scale. This particular example is of an appropriate size and subject to have hung in the home of a wealthy family.</p>\n",
      "dimensions": "362.7 × 285.8 cm (142 7/8 × 112 1/2 in.)",
      "medium_display": "Wool and silk, slit and double interlocking tapestry weave.\nWarp: Count: 5 warps per cm; wool: S-ply of three Z-spun elements; diameters: 0.9–1.2 mm\nWeft: Count: varies from 11 to 34 wefts per cm; wool: S-ply of two, three, and four Z-spun elements; diameters: 0.7–1.7 mm; silk: pairs of S-ply of two Z-twisted elements; diameters: 0.7–1.2 mm",
      "credit_line": "Gift of Kate S. Buckingham",
      "provenance_text": "An unidentified European family, to 1920; sold to Jacques Seligmann and Company, Paris, 1920; transferred to Jacques Seligmann and Company, New York, Nov. 3. 1920; sold to Kate S. Buckingham (died 1937), Chicago, April 6, 1922 [invoice, Apr. 6, 1922, no. 1457, copy in curatorial object file; on loan to the Art Institute of Chicago from May 20, 1922, incoming receipt R490, loan number 2499.22]; given to the Art Institute, 1922",
      "artwork_type_title": "Textile",
      "artist_id": null,
      "artist_title": null,
      "term_titles": "[\"weaving - tapestry\",\"wool (textile)\",\"textile\"]",
      "image_id": "cd0f60d9-2f55-d570-ba9b-fc74f31b0ef3",
      "alt_text": "A work made of wool and silk, slit and double interlocking tapestry weave.\nwarp: count: 5 warps per cm; wool: s-ply of three z-spun elements; diameters: 0.9–1.2 mm\nweft: count: varies from 11 to 34 wefts per cm; wool: s-ply of two, three, and four z-spun elements; diameters: 0.7–1.7 mm; silk: pairs of s-ply of two z-twisted elements; diameters: 0.7–1.2 mm."
    },
    {
      "id": 94841,
      "title": "The Song of the Lark",
      "date_start": 1884,
      "date_end": 1884,
      "artist_display": "Jules Breton (French, 1827–1906)",
      "place_of_origin": "France",
      "description": "<p>A lone peasant girl pauses her work to listen to a lark singing in the distance. Her emotional response to this moment of natural beauty is accentuated by the glow of the sun rising behind her, suffusing the landscape with golden light.</p>\n<p>Jules Breton specialized in scenes of rustic life in the countryside. Having been raised in the rural village of Courrières in northern France, he admired the people living there for their resourcefulness and connection to nature and gained immense popularity by painting them in his idealized style.</p>\n",
      "dimensions": "110.6 × 85.8 cm (43 1/2 × 33 3/4 in.); Framed: 142.3 × 116.9 cm (56 × 46 in.)",
      "medium_display": "Oil on canvas",
      "credit_line": "Henry Field Memorial Collection",
      "provenance_text": "Bought from the artist by George A. Lucas, Paris, for Samuel P. Avery in 1885 [this and the following information according to Omaha 1982-83]; sold to Henry Field (died 1890), Chicago, 1885; by descent to his wife, Mrs. Florence Lathrop Field; transferred to the Art Institute in October 1894; given to the Art Institute, 1916.",
      "artwork_type_title": "Painting",
      "artist_id": 33753,
      "artist_title": "Jules Breton",
      "term_titles": "[\"oil on canvas\",\"oil paint (paint)\",\"oil painting\",\"19th century\",\"woman\",\"sky\",\"horizon\",\"landscape\",\"rural life\",\"french\",\"oil paintings (visual works)\",\"paint\",\"canvas\",\"paint\",\"painting\",\"painting\",\"painting (image making)\",\"painting techniques\",\"bird\",\"farm\",\"field\",\"girl\",\"labor\",\"peasants\",\"sun\",\"sunrises\",\"painting\",\"european painting\"]",
      "image_id": "48b2de88-ba73-8e19-f448-d1cef4a1c847",
      "alt_text": "A work made of oil on canvas."
    },
    {
      "id": 81239,
      "title": "The Chofu Jewel River, one of the Six Jewel Rivers (Mu Tamagawa)",
      "date_start": 1801,
      "date_end": 1834,
      "artist_display": "Katsushika Hokusai 葛飾 北斎\nJapanese, 1760-1849",
      "place_of_origin": "Japan",
      "description": null,
      "dimensions": "20 × 53.8 cm (7 7/8 × 21 3/16 in.)",
      "medium_display": "Color woodblock print; long surimono",
      "credit_line": "Gift of Helen C. Gunsaulus",
      "provenance_text": null,
      "artwork_type_title": "Print",
      "artist_id": 31492,
      "artist_title": "Katsushika Hokusai",
      "term_titles": "[\"woodblock print\",\"print\",\"asian art\"]",
      "image_id": "98ddc3c7-d0f2-92bb-2d71-e8589f7608a6",
      "alt_text": "A work made of color woodblock print; long surimono."
    },
    {
      "id": 47677,
      "title": "A View of Timber Yards from a Bridge",
      "date_start": 1840,
      "date_end": 1850,
      "artist_display": "Utagawa Hiroshige 歌川 広重\nJapanese, 1797-1858",
      "place_of_origin": "Japan",
      "description": null,
      "dimensions": "24.4 × 30.2 cm (9 1/8 × 11 3/8 in.)",
      "medium_display": "Color woodblock print; uchiwa-e",
      "credit_line": "Kate S. Buckingham Endowment",
      "provenance_text": null,
      "artwork_type_title": "Print",
      "artist_id": 34946,
      "artist_title": "Utagawa Hiroshige",
      "term_titles": "[\"woodblock print\",\"Japanese (culture or style)\",\"print\",\"asian art\"]",
      "image_id": "6b072cd6-4b7d-c91f-3ad4-6ad877944ed3",
      "alt_text": "A work made of color woodblock print; uchiwa-e."
    },
    {
      "id": 202593,
      "title": "Hateha",
      "date_start": 1967,
      "date_end": 1968,
      "artist_display": "James Falconer\nAmerican, 1943-2022",
      "place_of_origin": "United States",
      "description": null,
      "dimensions": "35.5 × 28 cm (14 × 11 1/16 in.)",
      "medium_display": "Color screenprint on white paper",
      "credit_line": "Print and Drawing Club Fund",
      "provenance_text": null,
      "artwork_type_title": "Print",
      "artist_id": 110896,
      "artist_title": "James Falconer",
      "term_titles": "[\"print\",\"paper (fiber product)\",\"prints and drawing\"]",
      "image_id": "eb41889f-06fa-c5e0-442a-fe3efa3da66e",
      "alt_text": "A work made of color screenprint on white paper."
    },
    {
      "id": 180242,
      "title": "Lichens on River Stones - South Coast",
      "date_start": 1972,
      "date_end": 1972,
      "artist_display": "Eliot Porter\nAmerican, 1901–1990",
      "place_of_origin": "United States",
      "description": null,
      "dimensions": "Image/paper: 27.1 × 20.8 cm (10 11/16 × 8 1/4 in.); Mount: 50.7 × 38.2 cm (20 × 15 1/16 in.)",
      "medium_display": "Dye imbibition print, from the portfolio \"Portfolio II Iceland\" (1975)",
      "credit_line": "Gift of David C. and Sarajean Ruttenberg",
      "provenance_text": null,
      "artwork_type_title": "Photograph",
      "artist_id": 36244,
      "artist_title": "Eliot Porter",
      "term_titles": "[\"photograph\",\"photography\"]",
      "image_id": "4acae0e3-4342-0b2d-171e-72eb555726a8",
      "alt_text": "A work made of dye imbibition print, from the portfolio \"portfolio ii iceland\" (1975)."
    },
    {
      "id": 124679,
      "title": "A Grove of Tamarack Pine, Near Timber Line",
      "date_start": 1921,
      "date_end": 1921,
      "artist_display": "Ansel Adams\nAmerican, 1902–1984",
      "place_of_origin": "United States",
      "description": null,
      "dimensions": "Image: 14.3 × 19.5 cm (5 11/16 × 7 11/16 in.); Paper: 25 × 30.2 cm (9 7/8 × 11 15/16 in.)",
      "medium_display": "Gelatin silver print, from the portfolio \"Parmelian Prints of the High Sierras\" (1927)",
      "credit_line": "Gift of Edward C. Porter",
      "provenance_text": null,
      "artwork_type_title": "Photograph",
      "artist_id": 33354,
      "artist_title": "Ansel Adams",
      "term_titles": "[\"gelatin silver (developing-out-paper) pr\",\"photographic paper\",\"Collected by Hugh Edwards\",\"black-and-white photography\",\"photographic process\",\"photography\",\"photograph\",\"photographic processes\",\"photographic techniques\",\"photography\"]",
      "image_id": "0b5c239b-f89d-45f1-92b5-3cff416d51c7",
      "alt_text": "A work made of gelatin silver print, from the portfolio \"parmelian prints of the high sierras\" (1927)."
    },
    {
      "id": 121709,
      "title": "El Capitan, Sunrise, Yosemite National Park",
      "date_start": 1956,
      "date_end": 1956,
      "artist_display": "Ansel Adams\nAmerican, 1902–1984",
      "place_of_origin": "United States",
      "description": null,
      "dimensions": "Image/paper: 24 × 18.6 cm (9 1/2 × 7 3/8 in.); Mount: 45.8 × 35.7 cm (18 1/16 × 14 1/16 in.)",
      "medium_display": "Gelatin silver print, No. 6 from \"Portfolio Three: Yosemite Valley\" (1959)",
      "credit_line": "Photography Gallery Fund",
      "provenance_text": null,
      "artwork_type_title": "Photograph",
      "artist_id": 33354,
      "artist_title": "Ansel Adams",
      "term_titles": "[\"gelatin silver (developing-out-paper) pr\",\"photographic paper\",\"Collected by Hugh Edwards\",\"black-and-white photography\",\"photographic process\",\"photography\",\"photograph\",\"photographic processes\",\"photographic techniques\",\"photography\"]",
      "image_id": "318c0462-d30f-10f1-e04d-ac92ec39be1d",
      "alt_text": "A work made of gelatin silver print, no. 6 from \"portfolio three: yosemite valley\" (1959)."
    },
    {
      "id": 180206,
      "title": "Statue of Horus",
      "date_start": -305,
      "date_end": -30,
      "artist_display": "Egyptian",
      "place_of_origin": "Egypt",
      "description": "<p>From the appearance of the first kings in Egypt (about 3000 BCE), the ruler was considered to be the earthly manifestation of Horus, the god of divine kingship. Statues of Horus in the form of a falcon like this one were displayed in temples as part of the royal cult, which celebrated the ruler’s role as an intercessor between humans and gods.</p>\n",
      "dimensions": "52 × 48.5 × 18.8 cm (20 1/2 × 19 × 7 3/8 in.)",
      "medium_display": "Basalt",
      "credit_line": "Gift of the Alsdorf Foundation",
      "provenance_text": "Jeanette Brun (dealer), Zürich, by 1966 [copy of letter to James W. Alsdorf dated November 21, 1966 in curatorial file]; sold to James W. Alsdorf, Chicago, 1966; given to the Art Institute, 2002.",
      "artwork_type_title": "Sculpture",
      "artist_id": 37541,
      "artist_title": "Ancient Egyptian",
      "term_titles": "[\"ptolemaic\",\"basalt (basic igneous rock)\",\"gods (deities)\",\"statue\",\"carving\",\"animals\",\"stone\",\"ancient art\",\"sculpture\",\"statuette\",\"ancient\",\"falcons\",\"egyptian\",\"stone\",\"birds\"]",
      "image_id": "6a766b86-824d-239b-e3b8-eea48af968ee",
      "alt_text": "A work made of basalt."
    },
    {
      "id": 221814,
      "title": "American Horizon",
      "date_start": 2000,
      "date_end": 2000,
      "artist_display": "Jane Wilson\nAmerican, 1924-2015",
      "place_of_origin": "United States",
      "description": null,
      "dimensions": "172 × 199.4 cm (67 3/4 × 78 1/2 in.)",
      "medium_display": "Oil on linen",
      "credit_line": "Gift of Maureen and Edward B. Smith, Jr.",
      "provenance_text": null,
      "artwork_type_title": "Painting",
      "artist_id": 60445,
      "artist_title": "Jane Wilson",
      "term_titles": "[\"painting\",\"21st Century\"]",
      "image_id": "4690a926-8782-d904-27ee-e38b400f7c87",
      "alt_text": "Abstract painting in vivid hues evoking a land- or seascape, featuring a large blue sky mottled by yellow and gold whispy clouds."
    },
    {
      "id": 158786,
      "title": "Necklace",
      "date_start": -850,
      "date_end": -750,
      "artist_display": "Chavín\nChavín de Huantar, north coast, Peru",
      "place_of_origin": "Chavín de Huantar",
      "description": null,
      "dimensions": "Approx. l: H.: 27.9 cm (11 in.)",
      "medium_display": "Rock crystal",
      "credit_line": "Alsdorf Foundation Fund",
      "provenance_text": null,
      "artwork_type_title": "Costume and Accessories",
      "artist_id": 30073,
      "artist_title": "Chavín",
      "term_titles": "[\"bead\",\"crystal (material by form)\",\"chavín horizon\",\"jewelry\",\"early horizon\",\"Pre-Columbian\",\"americas\",\"art of the americas\",\"jewelry\",\"elite\",\"andes\",\"costume\",\"Arts of the Americas\",\"andean\",\"status\"]",
      "image_id": "3a9d26e0-4016-b6fc-2059-48560dce7ddc",
      "alt_text": "A work made of rock crystal."
    },
    {
      "id": 146953,
      "title": "Two Cows and a Young Bull beside a Fence in a Meadow",
      "date_start": 1647,
      "date_end": 1647,
      "artist_display": "Paulus Potter (Dutch, 1625–1654)",
      "place_of_origin": "Netherlands",
      "description": "<p>Paulus Potter, a prolific painter and etcher during his short life, elevated images of cows, oxen, and other domestic animals to majestic emblems of nature. His lavish attention to the physical appearances of such beasts—the varied texture and coloring of their hair, their characteristic poses, their bulky contours—borders on portraiture and likely derived from drawings he made from life. With Potter, animal painting blossomed into an independent genre in the Dutch Republic.</p>\n",
      "dimensions": "49.5 × 37.2 cm (19 1/2 × 14 3/4 in.); Framed: 70.2 × 58.1 × 4.5 cm (27 5/8 × 22 7/8 × 1 3/4 in.)",
      "medium_display": "Oil on panel",
      "credit_line": "In loving memory of Harold T. Martin from Eloise W. Martin, wife, and Joyce Martin Brown, daughter; Charles H. and Mary F.S. Worcester Collection; Lacy Armour Endowment; through prior gift of Frank H. and Louise B. Woods",
      "provenance_text": "Probably Dr. Simons, Leiden, by 1763; sold Leyden, Pieter van der Eyk, 29 April 1763, no. 18, “Een Wonder schoon Kunststuk met drie graazende Koeyen in een fraay Landscape uitvoerig en aangenaam geschilderd door den beroemden Paulus Potter 16 x 17 duimen” [according to a note by the Leiden collector Van der Marck in a copy of the Caauw sale catalogue in the Bibliothèque nationale de France, Paris; see Bille, vol. 2, p. 112].  Probably Frans van Mieris the Younger, Leiden, by 1764; sold Leiden, Pieter van der Eyk, 7 May, 1764, no. 82, with the same description as in the preceding sale catalogue, but with dimensions given as 16 ½ x 14 ? duimen, for 570 guilders to Caauw [according to an annotated sale catalogue in the R.K.D., The Hague, and the annotated copy of the Caauw sale catalogue cited above].  Probably Pieter Caauw; his sale Leiden, Luchtmans, August 24, 1768, no. 1, “Een leggende en twee staande koeijen”, 16 ? x 14 ½ d., on panel, sold for 670 guilders to Jan Matthias Kok, Amsterdam [annotated sale catalogues in the R.K.D. and the Bibliotheque nationale de France].  Gerret Braamcamp, Amsterdam (died 1771); sold Amsterdam, Van der Schley et al., 31 July, 1771, no. 169, to Yver for 2,070 guilders. Pieter de Smeth van Alphen, Amsterdam (died 1810); offered for sale Amsterdam, Van der Schley et al., 1-2 August 1810, no. 75, bid of 3,600 guilders by de Vries, but bought in [see Priem 1997, p. 136]; offered again in the sale of the collection of Henry Croese, Amsterdam, Van der Schley et al., 18 September, 1811, no. 67 to J. Smit for 2,400 guilders [annotated sale catalogue in the Frick Art Reference Library and Priem 1997].  Anna Maria Hogguer-Ebeling, Amsterdam (died 1812); to her husband, Paul Iwan Hogguer, Amsterdam (died 1816); sold, Amsterdam, Van der Schley et al., 18 August, 1817, no. 67 to Antoine Jolli as agent for William Buchanan for 7,925 guilders [annotated sale catalogue in Ryerson library and Buchanan 1824]; sold by William Buchanan, London, to George Watson Taylor, London and Erlestoke Park, near Devizes, Wiltshire; offered for sale, Christie’s, London, June 13-14, 1823, no. 58 of second day, but repurchased at 1,210 gns.; sold George Robins, Erlestoke Park, Wiltshire, 9 July-1 August 1832, no. 75 to C. J. Niewenhuys [according to Smith 1834]; his sale, Christie’s, London, 10 May 1833, no. 70, to Walmesley for 1,155 gns. [according to Hofstede de Groot 1912; Smith 1834 stated that it was bought in for 1,105 gns].  John Walter, Bearwood, near Wokenham, by 1834 [according to Smith 1834]; by descent to John Walter, until 1942; sold, Sotheby’s, London, 10 June, 1942, no. 49, to Duits for £3,500 [according to Sotheby’s catalogue of the Fattorini sale].  John Enrico Fattorini, Bradford, by 1945 (died 1949) [lent to London 1945]; by descent to his son E.W. Fattorini, Bradford (died 1992); sold by his heirs, Sotheby’s, London, 3 July, 1996, no. 11, to Otto Naumann, Ltd, New York; sold by Otto Naumann, Ltd to the Art Institute, 1997.",
      "artwork_type_title": "Painting",
      "artist_id": 36253,
      "artist_title": "Paulus Potter",
      "term_titles": "[\"oil on panel\",\"oil paint (paint)\",\"oil painting\",\"cows\",\"Realism\",\"animals\",\"paint\",\"organic material\",\"paint\",\"painting\",\"panel (wood)\",\"painting\",\"painting (image making)\",\"painting techniques\",\"panel painting\",\"17th Century\",\"clouds\",\"fences\",\"landscape\",\"sky\",\"trees\",\"painting\",\"european painting\",\"Naturalism\"]",
      "image_id": "5de78980-17d7-8fb5-83de-7b2ae4e997f2",
      "alt_text": "A tired-looking brown and white cow lies down on a patch of dry earth, a dark-brown bull and cow standing behind her against an overcast sky."
    },
    {
      "id": 111661,
      "title": "The End of the Trail",
      "date_start": 1918,
      "date_end": 1918,
      "artist_display": "James Earle Fraser (American, 1876–1953)\nCast by Gorham Co. Founders",
      "place_of_origin": "United States",
      "description": "<p><em>The End of the Trail</em>, James Earle Fraser’s best-known sculpture, has come to symbolize the genocide of Native American peoples amid relentless westward expansion. In 1894, the year after the World’s Columbian Exposition in Chicago, the 17-year-old Fraser, then a student at the School of the Art Institute, produced the first version of this bronze sculpture. (The Art Institute’s sculpture is a later model and cast.) Reenforcing the conception of the so-called vanishing Indian, the work portrays an exhausted Sioux drooping over his equally weary pony; both rider and horse have reached the end of the trail.</p>\n",
      "dimensions": "H.: 111.8 cm (44 in.)",
      "medium_display": "Bronze",
      "credit_line": "Bequest of Arthur Rubloff Trust",
      "provenance_text": null,
      "artwork_type_title": "Sculpture",
      "artist_id": 8766,
      "artist_title": "James Earle Fraser",
      "term_titles": "[\"bronze\",\"sculpture\",\"Chicago\",\"american arts\",\"animals\",\"people\",\"portraits\"]",
      "image_id": "e5441c64-1b7a-d4b6-ed29-293e164e4f0b",
      "alt_text": "A work made of bronze."
    },
    {
      "id": 136034,
      "title": "On the War Trail",
      "date_start": 1915,
      "date_end": 1925,
      "artist_display": "Alexander Phimister Proctor (American, born Canada, 1862–1950)\nCast by Roman Bronze Works (American, founded 1897)",
      "place_of_origin": "New York City",
      "description": "<p>Canadian-born Alexander Phimister Proctor began his career as a sculptor of animals and, along with Edward Kemeys, achieved recognition for the works he created for Chicago’s 1893 World’s Columbian Exposition. During five years of study in France afterward, however, Proctor shifted his interests to large-scale figural studies, particularly of the American West. <em>On the War Trail</em> is a reduced version of a monumental bronze commissioned for the Civic Center in Denver, Colorado. Dignified and erect, with the Native American’s spear thrust defiantly outward, horse and rider provide a striking antidote to the dejected, broken subject of James Earle Fraser’s <a href=\"https://www.artic.edu/artworks/111661\"><em>The End of the Trail</em></a> (1991.325).</p>\n",
      "dimensions": "H.: 121.9 cm (48 in.)",
      "medium_display": "Bronze",
      "credit_line": "Bequest of Arthur Rubloff",
      "provenance_text": null,
      "artwork_type_title": "Sculpture",
      "artist_id": 32516,
      "artist_title": "Alexander Phimister Proctor",
      "term_titles": "[\"bronze\",\"sculpture\",\"Chicago\",\"american arts\",\"animals\",\"people\",\"portraits\"]",
      "image_id": "ad61f134-f065-557d-bff3-60e3ef135c2e",
      "alt_text": "A work made of bronze."
    },
    {
      "id": 5370,
      "title": "Mummy Mask",
      "date_start": -100,
      "date_end": -1,
      "artist_display": "Paracas\nSouth coast, Peru",
      "place_of_origin": "Peru",
      "description": null,
      "dimensions": "24.9 × 23.1 cm (9 13/16 × 9 1/8 in.) (without extended warps)",
      "medium_display": "Cotton, plain weave with bundles of extended warps; painted",
      "credit_line": "Simeon B. Williams Fund",
      "provenance_text": "Pablo Soldi, Ica, Peru, by 1957 [via Pan American Shop, New York; incoming receipt Rx2213, Apr. 26, 1957, copy in curatorial object file]; sold to the Art Institute of Chicago, 1957.",
      "artwork_type_title": "Textile",
      "artist_id": 20363,
      "artist_title": "Paracas",
      "term_titles": "[\"ocucaje\",\"cotton (fiber)\",\"textile\",\"weaving - printed\",\"paracas\",\"early horizon\",\"Pre-Columbian\",\"peruvian\",\"andean\",\"andes\",\"super/natural\"]",
      "image_id": "e6c5ebc4-7c7d-a80f-4c4c-1f610ae076b6",
      "alt_text": "A work made of cotton, plain weave with bundles of extended warps; painted."
    },
    {
      "id": 217140,
      "title": "Cool Breeze (Sofu)",
      "date_start": 1993,
      "date_end": 1993,
      "artist_display": "Yoshida Chizuko\nJapanese, 1924-2017",
      "place_of_origin": "Japan",
      "description": "<p>Here, Yoshida Chizuko has combined woodblock printing with photoetching—an engraving technique—to show a lavender field moving in a cool breeze.  Chizuko was interested in finding patterns in nature, and close observation enabled her to infuse her work with a sense of movement.</p>\n",
      "dimensions": "100.5 × 41.5 cm (39 5/8 × 16 3/8 in.)",
      "medium_display": "Photoetching and color woodblock print",
      "credit_line": "Gift of Chizuko, Takasuke, and Ayomi Yoshida",
      "provenance_text": null,
      "artwork_type_title": "Print",
      "artist_id": 37392,
      "artist_title": "Yoshida Chizuko",
      "term_titles": "[\"woodblock print\",\"landscapes\",\"Japanese (culture or style)\",\"print\"]",
      "image_id": "ba45d095-af9c-c759-3bcb-4e316f9f613d",
      "alt_text": "A work made of photoetching and color woodblock print."
    },
    {
      "id": 118048,
      "title": "Breeze at Work",
      "date_start": 1987,
      "date_end": 1987,
      "artist_display": "Sandy Skoglund\nAmerican, born 1946",
      "place_of_origin": "United States",
      "description": null,
      "dimensions": "Image/paper, approx: 95 × 136 cm (37 7/16 × 53 9/16 in.); 117.5 × 158 × 4 cm (46 5/16 × 62 1/4 × 1 5/8 in.)",
      "medium_display": "Silver dye-bleach print",
      "credit_line": "Gift of David C. and Sarajean Ruttenberg",
      "provenance_text": null,
      "artwork_type_title": "Photograph",
      "artist_id": 42845,
      "artist_title": "Sandy Skoglund",
      "term_titles": "[\"silver-dye bleach print\",\"interiors\",\"conceptual\",\"photography\",\"photographic process\",\"photography\",\"photograph\"]",
      "image_id": "e8fc1a78-2f80-b9dc-2a9d-05896eb5f621",
      "alt_text": "A work made of silver dye-bleach print."
    },
    {
      "id": 11058,
      "title": "Study: Head of a Young Girl Facing to the Left",
      "date_start": 1705,
      "date_end": 1755,
      "artist_display": "Carle van Loo\nFrench, 1705-1765",
      "place_of_origin": "France",
      "description": null,
      "dimensions": "23.4 × 18.2 cm (9 1/4 × 7 3/16 in.)",
      "medium_display": "Pastel, with touches of black crayon and red chalk, on blue laid paper, laid down on blue wove paper, laid down on cream wove paper",
      "credit_line": "Gift of the Joseph and Helen Regenstein Foundation",
      "provenance_text": "Edmond (died 1896) and Jules Goncourt (died 1870), Paris; sold, February 15, 1897, lot 330 [according to Joachim 1977].  Comtesse Pélhion [according to Joachim 1977].  Sold by the Charles E. Slatkin Gallery, New York, to the Art Institute, 1959.",
      "artwork_type_title": "Drawing and Watercolor",
      "artist_id": 40876,
      "artist_title": "Carle van Loo",
      "term_titles": "[\"pastel\",\"paper (fiber product)\",\"chalk sticks\",\"pastels (crayons)\",\"crayons\",\"drawings (visual works)\",\"prints and drawing\"]",
      "image_id": "1ca72da2-ab67-dbee-a0c6-8e7a04f2b6c5",
      "alt_text": "A work made of pastel, with touches of black crayon and red chalk, on blue laid paper, laid down on blue wove paper, laid down on cream wove paper."
    },
    {
      "id": 182262,
      "title": "Horizon B (Suihen B)",
      "date_start": 1973,
      "date_end": 1973,
      "artist_display": "Iwami Reika (Japanese, 1927–2020)",
      "place_of_origin": "Japan",
      "description": "<p>Iwami Reika was a sculptor before turning to prints, and the woodgrain seen here features prominently in her compositions. She would apply ink to pieces of driftwood or old wood before pressing them to the paper. While creating this work, she sprinkled powdered mica, a sparkling mineral, over the wet ink; it can be seen on most of the printed areas. Iwami affixed the gold leaf in a similar fashion. The heavy embossing seen here in the round, moon-like form began to appear in her prints after 1969.</p>\n",
      "dimensions": "62 × 68.8 cm (24 7/16 × 27 1/16 in.)",
      "medium_display": "Woodblock print with gold foil",
      "credit_line": "Gift of Marguerite Michaels",
      "provenance_text": null,
      "artwork_type_title": "Print",
      "artist_id": 21542,
      "artist_title": "Iwami Reika",
      "term_titles": "[\"woodblock print\",\"paper (fiber product)\",\"Japanese (culture or style)\",\"print\",\"woodblock\"]",
      "image_id": "e3735f3b-0f1b-d0bf-7f1a-85eb0ca58f03",
      "alt_text": "A work made of woodblock print with gold foil."
    },
    {
      "id": 97657,
      "title": "Savage Breeze",
      "date_start": 1974,
      "date_end": 1974,
      "artist_display": "Helen Frankenthaler (American, 1928-2011)\nprinted by Bill Goldston (American, born 1943) and Juda Rosenberg (American)\npublished by Universal Limited Art Editions (American, founded 1955)",
      "place_of_origin": "United States",
      "description": "<p><em>Savage Breez</em> frustrated Frankenthaler more than any other print she produced at Universal Limited Art Editions (U.L.A.E.). She recalled:<br><em>Savage Breeze</em> went dead like a lead balloon. So after many tries, I finally said, let’s scratch it. I was almost exasperated. I couldn’t get the light I desired. I knew the drawing was right. I knew the scale was right. Then I thought—why don’t we whitewash the paper first and then print the other colors I’d mixed over it. We did. And it glowed.</p>\n",
      "dimensions": "Sheet: 79.9 × 67.8 cm (31 1/2 × 26 3/4 in.)",
      "medium_display": "Color woodcut from eight lauan mahogany plywood blocks on buff laminated Nepalese paper",
      "credit_line": "U.L.A.E. Collection acquired through a challenge grant of Mr. and Mrs. Thomas Dittmer; purchased with funds provided by supporters of the Department of Prints and Drawings; Centennial Endowment; Margaret Fisher Endowment Fund",
      "provenance_text": null,
      "artwork_type_title": "Print",
      "artist_id": 8741,
      "artist_title": "Helen Frankenthaler",
      "term_titles": "[\"woodcut\",\"paper (fiber product)\",\"print\",\"prints and drawing\"]",
      "image_id": "74a954d1-46a5-dee8-c642-d18381ab0764",
      "alt_text": "A work made of color woodcut from eight lauan mahogany plywood blocks on buff laminated nepalese paper."
    },
    {
      "id": 71936,
      "title": "The End of the Timber Line",
      "date_start": 1884,
      "date_end": 1950,
      "artist_display": "Charles William Dahlgreen\nAmerican, 1864-1955",
      "place_of_origin": "United States",
      "description": null,
      "dimensions": null,
      "medium_display": "Etching on paper",
      "credit_line": "Bequest of Lessing Rosenthal",
      "provenance_text": null,
      "artwork_type_title": "Print",
      "artist_id": 34119,
      "artist_title": "Charles William Dahlgreen",
      "term_titles": "[\"etching\",\"paper (fiber product)\",\"print\",\"prints and drawing\"]",
      "image_id": "cb1ad1f4-3fca-1f95-22d4-f2c111e38bc8",
      "alt_text": "A work made of etching on paper."
    },
    {
      "id": 2171,
      "title": "Salisbury Cathedral from the Meadows: the Rainbow",
      "date_start": 1834,
      "date_end": 1834,
      "artist_display": "David Lucas (English, 1802-1881)\nafter John Constable (English, 1776-1837)",
      "place_of_origin": "England",
      "description": "<p>The landscape painter John Constable owned an edition of J. M. W. Turner’s <em>Liber Studiorum</em>, which he famously referred to as the “liber stupidorum,” a critical remark directed at the ambitious size of the undertaking (of which only 71 of the planned 100 plates were finally printed), rather than its artistry. Constable nonetheless employed David Lucas’s considerable printmaking talents to immortalize 22 of his own paintings in mezzotint for a similarly scaled portfolio,  <em>English Landscape Scenery</em>. They also collaborated on this larger plate, revising it until Constable’s death, as the artist agonized over every detail, explaining in a letter to Lucas: “If [the rainbow] is not tender—and elegant—evanescent and lovely . . . we are both ruined.”</p>\n",
      "dimensions": "Image: 55.2 × 68.9 cm (21 3/4 × 27 3/16 in.); Sheet: 61.6 × 71.2 cm (24 5/16 × 28 1/16 in.)",
      "medium_display": "Mezzotint with etching, in black, on cream wove paper",
      "credit_line": "John H. Wrenn Fund",
      "provenance_text": null,
      "artwork_type_title": "Print",
      "artist_id": 35522,
      "artist_title": "David Lucas",
      "term_titles": "[\"mezzotint\",\"landscapes\",\"paper (fiber product)\",\"print\",\"prints and drawing\"]",
      "image_id": "54c8b002-99a8-a416-f4e7-a0126e1e5c98",
      "alt_text": "A work made of mezzotint with etching, in black, on cream wove paper."
    },
    {
      "id": 3070,
      "title": "Elector Frederick III of Saxony, from Speculum intellectuale felicitatis humane",
      "date_start": 1510,
      "date_end": 1510,
      "artist_display": "Wolf Traut (German, c.1486-1520)\nafter Lucas Cranach the Elder (German, 1472-1553)\npublished by Hieronymus Höltzel (German, active c. 1502-1525)",
      "place_of_origin": "Germany",
      "description": null,
      "dimensions": "Image/block: 12.7 × 9.6 cm (5 × 3 13/16 in.)",
      "medium_display": "Woodcut in black on ivory laid paper",
      "credit_line": "Gift of Mr. and Mrs. Potter Palmer",
      "provenance_text": null,
      "artwork_type_title": "Print",
      "artist_id": 44665,
      "artist_title": "Wolf Traut",
      "term_titles": "[\"woodcut\",\"paper (fiber product)\",\"woodcut (process)\",\"print\",\"prints and drawing\"]",
      "image_id": "45944c93-e51d-dd15-7853-4a99717d0e51",
      "alt_text": "A work made of woodcut in black on ivory laid paper."
    },
    {
      "id": 3796,
      "title": "The Falconer and the Lady",
      "date_start": 1495,
      "date_end": 1503,
      "artist_display": "Israhel van Meckenem the Younger\nGerman, c. 1440/45-1503",
      "place_of_origin": "Germany",
      "description": "<p>In the fifteenth century, prints were frequently published with conspicuously empty banderoles, blanks that viewers could complete by adding titles or fill in as early thought or speech bubbles. Israhel van Meckenem employed these winding, decorative banners to draw viewers into his coyly provocative <em>Falconer and Lady</em> and other images from his series of twelve secular couples involved in everyday activities, from church-going to playing music. These courtly lovers wear sumptuous clothing and participate in falconry, a popular hunting pastime of the wealthy. The hooded bird may symbolize the lovers’ cautious restraint.</p>\n",
      "dimensions": "16.6 × 11.6 cm (6 9/16 × 4 5/8 in.)",
      "medium_display": "Engraving in black on cream laid paper",
      "credit_line": "Bequest of Mrs. Potter Palmer, Jr.",
      "provenance_text": null,
      "artwork_type_title": "Print",
      "artist_id": 37116,
      "artist_title": "Israhel van Meckenem, the younger",
      "term_titles": "[\"engraving\",\"paper (fiber product)\",\"print\",\"prints and drawing\"]",
      "image_id": "f36ba797-0ff1-d6dc-8744-2f54888dbc89",
      "alt_text": "A work made of engraving in black on cream laid paper."
    },
    {
      "id": 8768,
      "title": "Bright Angel Trail",
      "date_start": 1922,
      "date_end": 1922,
      "artist_display": "Gustave Baumann\nAmerican, 1881-1971",
      "place_of_origin": "United States",
      "description": null,
      "dimensions": "Image: 24.4 × 28.7 cm (9 5/8 × 11 5/16 in.); Sheet: 34.2 × 41.8 cm (13 1/2 × 16 1/2 in.)",
      "medium_display": "Color woodcut on tan laid paper",
      "credit_line": "The William Gold Hibbard Memorial",
      "provenance_text": null,
      "artwork_type_title": "Print",
      "artist_id": 33550,
      "artist_title": "Gustave Baumann",
      "term_titles": "[\"woodcut\",\"woodcut (process)\",\"paper (fiber product)\",\"printing\",\"print\",\"prints and drawing\"]",
      "image_id": "bdf92a5c-ef9c-378f-13c0-dc071fc52614",
      "alt_text": "A work made of color woodcut on tan laid paper."
    },
    {
      "id": 8765,
      "title": "Bright Angel Trail",
      "date_start": 1922,
      "date_end": 1922,
      "artist_display": "Gustave Baumann\nAmerican, 1881-1971",
      "place_of_origin": "United States",
      "description": "<p>This print presents artistic paeans to the American Southwest and reflects the body of work Baumann produced during his trip to the Grand Canyon in 1921. <em>Bright Angel Trail</em> captures a view from the Bright Angel hiking trail, Baumann depicted the canyon’s craggy peaks and steep walls with vivid tones of russet, purple, and green.</p>\n",
      "dimensions": "Image: 24.3 × 28.7 cm (9 5/8 × 11 5/16 in.); Sheet: 34.2 × 42.5 cm (13 1/2 × 16 3/4 in.)",
      "medium_display": "Color woodcut on cream laid paper",
      "credit_line": "The William Gold Hibbard Memorial",
      "provenance_text": null,
      "artwork_type_title": "Print",
      "artist_id": 33550,
      "artist_title": "Gustave Baumann",
      "term_titles": "[\"woodcut\",\"woodcut (process)\",\"paper (fiber product)\",\"printing\",\"print\",\"prints and drawing\"]",
      "image_id": "9f004f54-4456-1803-b668-0512850676a1",
      "alt_text": "A work made of color woodcut on cream laid paper."
    },
    {
      "id": 8860,
      "title": "Summer Breezes",
      "date_start": 1916,
      "date_end": 1916,
      "artist_display": "Gustave Baumann\nAmerican, 1881-1971",
      "place_of_origin": "United States",
      "description": null,
      "dimensions": "Image/block: 28 × 25.3 cm (11 1/16 × 10 in.); Sheet: 43 × 34.6 cm (16 15/16 × 13 5/8 in.)",
      "medium_display": "Color woodcut on cream laid paper",
      "credit_line": "The William Gold Hibbard Memorial",
      "provenance_text": null,
      "artwork_type_title": "Print",
      "artist_id": 33550,
      "artist_title": "Gustave Baumann",
      "term_titles": "[\"woodcut\",\"paper (fiber product)\",\"print\",\"prints and drawing\"]",
      "image_id": "febdde64-f4a7-02a4-fab2-ca47fd75455b",
      "alt_text": "A work made of color woodcut on cream laid paper."
    },
    {
      "id": 8858,
      "title": "Summer Breezes",
      "date_start": 1916,
      "date_end": 1916,
      "artist_display": "Gustave Baumann\nAmerican, 1881-1971",
      "place_of_origin": "United States",
      "description": null,
      "dimensions": "Image/block: 28 × 25.3 cm (11 1/16 × 10 in.); Primary support: 30.5 × 28 cm (12 1/16 × 11 1/16 in.); Secondary support: 40.1 × 35 cm (15 13/16 × 13 13/16 in.)",
      "medium_display": "Color woodcut on cream wove paper, tipped at top two corners onto cream laid paper",
      "credit_line": "The William Gold Hibbard Memorial",
      "provenance_text": null,
      "artwork_type_title": "Print",
      "artist_id": 33550,
      "artist_title": "Gustave Baumann",
      "term_titles": "[\"woodcut\",\"paper (fiber product)\",\"print\",\"prints and drawing\"]",
      "image_id": "9f1798a9-ddfe-4357-f1d0-376ef3bcc875",
      "alt_text": "A work made of color woodcut on cream wove paper, tipped at top two corners onto cream laid paper."
    },
    {
      "id": 9389,
      "title": "Fragment (Border)",
      "date_start": -100,
      "date_end": 200,
      "artist_display": "Paracas Necropolis\nPeru, south coast, Paracas Peninsula",
      "place_of_origin": "Peru",
      "description": null,
      "dimensions": "a: 62.2 × 16.5 cm (24 1/2 × 6 1/2 in.); b: 59.7 × 10.2 cm (23 1/2 × 4 in.); c: 55.9 × 10.2 cm (22 × 4 in.)",
      "medium_display": null,
      "credit_line": "Gift of Alan R. Sawyer",
      "provenance_text": null,
      "artwork_type_title": "Textile",
      "artist_id": 81503,
      "artist_title": "Paracas Necropolis",
      "term_titles": "[\"paracas necropolis\",\"textile\",\"needlework (visual works)\",\"early intermediate period\",\"paracas\",\"early horizon\",\"Pre-Columbian\",\"americas\",\"peruvian\",\"andean\",\"andes\"]",
      "image_id": "9db119da-ded6-a3d7-ea54-61fa60fe8a8d",
      "alt_text": "A work."
    },
    {
      "id": 23075,
      "title": "Cavalry Exercise in a Meadow",
      "date_start": 1855,
      "date_end": 1870,
      "artist_display": "Constantin Guys\nFrench, 1802-1892",
      "place_of_origin": "France",
      "description": null,
      "dimensions": "15.8 × 26 cm (6 1/4 × 10 1/4 in.)",
      "medium_display": "Pen and brown ink with brush and watercolor, on ivory wove paper",
      "credit_line": "Olivia Shaler Swan Fund",
      "provenance_text": "Sir Bruce Ingram, (b. 1877).  Sold by Richard Zinser, New York, to the Art Institute, 1965.",
      "artwork_type_title": "Drawing and Watercolor",
      "artist_id": 34778,
      "artist_title": "Constantin Guys",
      "term_titles": "[\"watercolor\",\"paper (fiber product)\",\"ink\",\"coating (material)\",\"watercolor\",\"water-base paint\",\"paint\",\"drawings (visual works)\",\"prints and drawing\"]",
      "image_id": "69c4fcd7-5553-2e13-a65f-da26ba84766d",
      "alt_text": "A work made of pen and brown ink with brush and watercolor, on ivory wove paper."
    },
    {
      "id": 40767,
      "title": "Ten Landscapes: Walled River Town to the Left of a River",
      "date_start": 1615,
      "date_end": 1616,
      "artist_display": "Esaias van de Velde I\nDutch, c. 1587-1630",
      "place_of_origin": "Holland",
      "description": null,
      "dimensions": "Image/plate: 8.7 × 17.7 cm (3 7/16 × 7 in.); Sheet: 9.7 × 18.7 cm (3 7/8 × 7 3/8 in.)",
      "medium_display": "Engraving in black on ivory laid paper",
      "credit_line": "Anonymous gift",
      "provenance_text": null,
      "artwork_type_title": "Print",
      "artist_id": 41233,
      "artist_title": "Esaias van den Velde, I",
      "term_titles": "[\"engraving\",\"paper (fiber product)\",\"print\",\"prints and drawing\"]",
      "image_id": "e14623bd-226c-3486-6334-337e74664307",
      "alt_text": "A work made of engraving in black on ivory laid paper."
    },
    {
      "id": 43259,
      "title": "Sunrise",
      "date_start": 1850,
      "date_end": 1850,
      "artist_display": "Charles François Daubigny\nFrench, 1817-1878",
      "place_of_origin": "France",
      "description": null,
      "dimensions": "Image: 13.4 × 23 cm (5 5/16 × 9 1/16 in.); Plate: 17.8 × 26.2 cm (7 1/16 × 10 3/8 in.)",
      "medium_display": "Etching on ivory wove paper",
      "credit_line": "The Charles Deering Collection",
      "provenance_text": null,
      "artwork_type_title": "Print",
      "artist_id": 40516,
      "artist_title": "Charles François Daubigny",
      "term_titles": "[\"etching\",\"paper (fiber product)\",\"print\",\"prints and drawing\"]",
      "image_id": "c9fa40c5-b0b4-37d0-2848-7b5fc9d3076e",
      "alt_text": "A work made of etching on ivory wove paper."
    },
    {
      "id": 49195,
      "title": "Maharana Bhim Singh in Procession",
      "date_start": 1815,
      "date_end": 1825,
      "artist_display": "India\nRajasthan, Mewar, Udaipur, attributed to Ghasi (active c. 1820-36)",
      "place_of_origin": "India",
      "description": "<p>In this dazzling royal procession, Maharana Bhim Singh (r. 1778-1828) rides across his kingdom, Mewar, on horseback. Richly bejeweled and tattooed, with his horse's reins in one hand and a hookah mouthpiece in the other, Bhim Singh deftly projects an image of power combined with pleasure and comfort. The leashed cheetah and falcon seem to be merely part of the large entourage arrayed around the ruler, which also contains men bearing royal standards and insignia, including a black solar disk with a gold sun in the center, a symbol of the once-proud Sisodia clan of Mewar.</p>\n<p>The magnificence of the scene belies the fact that Bhim Singh was actually a weak ruler in a succession of ineffectual leaders. Mewar had once been considered the strongest Rajput state because of its lengthy resistance to the Mughal emperors, but in 1818 Bhim Singh was forced to sign a treatey with the British, accepting their protection.</p>\n",
      "dimensions": "Image: 57.1 × 41.6 cm (22 1/2 × 16 3/8 in.); Paper: 60.7 × 45.6 cm (23 7/8 × 18 in.)",
      "medium_display": "Opaque watercolor and gold on paper",
      "credit_line": "Everett and Ann McNear Collection",
      "provenance_text": null,
      "artwork_type_title": "Painting",
      "artist_id": 105100,
      "artist_title": "Ghasi",
      "term_titles": "[\"miniature painting\",\"paper (fiber product)\",\"painting (image making)\",\"royal personages\",\"South Asian\",\"gold\",\"watercolor\",\"painting\",\"asian art\",\"tattoos\",\"swords\",\"smoking\",\"men\",\"jewelry\",\"falcons\",\"cheetahs\",\"Indian (South Asian)\",\"weapons\",\"Rana\",\"leopards\",\"horses\",\"animals\"]",
      "image_id": "9f08b895-4960-4bc6-5871-dc9bfab4c655",
      "alt_text": "Watercolor of man with golden halo on horse, green background."
    },
    {
      "id": 50785,
      "title": "Excitement",
      "date_start": 1886,
      "date_end": 1891,
      "artist_display": "Frank Meadow Sutcliffe\nEnglish, 1853–1941",
      "place_of_origin": "England",
      "description": null,
      "dimensions": "Image: 11.9 × 18.6 cm (4 11/16 × 7 3/8 in.); Paper: 28 × 38 cm (11 1/16 × 15 in.)",
      "medium_display": "Photogravure, from \"Sun Artists, Number 8\" (1891)",
      "credit_line": "Purchased with funds provided by Lucia Woods",
      "provenance_text": null,
      "artwork_type_title": "Photograph",
      "artist_id": 25264,
      "artist_title": "Frank Meadow Sutcliffe",
      "term_titles": "[\"photogravure\",\"19th century\",\"photomechanical process\",\"photography\",\"photograph\"]",
      "image_id": "3e2d5401-00fc-9536-3756-15256007d78b",
      "alt_text": "A work made of photogravure, from \"sun artists, number 8\" (1891)."
    },
    {
      "id": 50783,
      "title": "Water Rats",
      "date_start": 1986,
      "date_end": 1986,
      "artist_display": "Frank Meadow Sutcliffe\nEnglish, 1853–1941",
      "place_of_origin": "England",
      "description": null,
      "dimensions": "Image: 12.6 × 17.7 cm (5 × 7 in.); Paper: 28 × 37.9 cm (11 1/16 × 14 15/16 in.)",
      "medium_display": "Photogravure, from \"Sun Artists, Number 8\" (1891)",
      "credit_line": "Purchased with funds provided by Lucia Woods",
      "provenance_text": null,
      "artwork_type_title": "Photograph",
      "artist_id": 25264,
      "artist_title": "Frank Meadow Sutcliffe",
      "term_titles": "[\"photogravure\",\"photomechanical process\",\"photography\",\"photograph\"]",
      "image_id": "5b55ec27-7cd3-d080-74e4-c8be9fad6104",
      "alt_text": "A work made of photogravure, from \"sun artists, number 8\" (1891)."
    },
    {
      "id": 61764,
      "title": "Sunrise with Columns",
      "date_start": 1975,
      "date_end": 1975,
      "artist_display": "Joseph Parker\nAmerican,1930–2009",
      "place_of_origin": "United States",
      "description": null,
      "dimensions": "213.3 × 304.8 cm (83 15/16 × 120 in.)",
      "medium_display": "Acrylic on canvas",
      "credit_line": "Purchased with funds provided by Solomon B. Smith and Mr. and Mrs. Edward Byron Smith, Jr.",
      "provenance_text": null,
      "artwork_type_title": "Painting",
      "artist_id": 36133,
      "artist_title": "Joseph Parker",
      "term_titles": "[\"painting\",\"sunrises\",\"modern and contemporary art\",\"trees\",\"plants\",\"coastal scenes\",\"landscapes\",\"columns\",\"geometric\",\"clouds\"]",
      "image_id": "44113804-ce2c-a0e8-786f-319ba4474a28",
      "alt_text": "A work made of acrylic on canvas."
    },
    {
      "id": 73345,
      "title": "Barn in Blue Haze",
      "date_start": 1979,
      "date_end": 1979,
      "artist_display": "Wolf Kahn\nAmerican, born 1927",
      "place_of_origin": "United States",
      "description": "<p>The barn represented in this drawing is repeatedly used by Wolf Kahn to study the interaction of color, light, and form. Like many of his contemporaries, Kahn worked <em>en plein air</em>, examining the structure from different angles, scales, and times of day to discover its varied meanings, much like Claude Monet did in his famous images of haystacks. When this drawing is viewed with other depictions of the barn, it is possible not only to reconstruct the building in the round, but also to understand Kahn’s perceptions of his surroundings and the different methods he used to explore them.</p>\n",
      "dimensions": "36.8 × 48.9 cm (14 1/2 × 19 5/16 in.)",
      "medium_display": "Pastel on white wove paper",
      "credit_line": "Jalane and Richard Davidson Collection",
      "provenance_text": null,
      "artwork_type_title": "Drawing and Watercolor",
      "artist_id": 13340,
      "artist_title": "Wolf Kahn",
      "term_titles": "[\"pastel\",\"paper (fiber product)\",\"pastels (crayons)\",\"crayons\",\"drawings (visual works)\",\"prints and drawing\"]",
      "image_id": "e1798e33-9bd6-b8e4-0903-df46eec7fbee",
      "alt_text": "A work made of pastel on white wove paper."
    },
    {
      "id": 80632,
      "title": "Timber Hauling, Devon I",
      "date_start": 1919,
      "date_end": 1919,
      "artist_display": "Thomas George Soper\nEnglish, 1870-1942",
      "place_of_origin": "England",
      "description": null,
      "dimensions": "Image/plate: 15 × 27.5 cm (5 15/16 × 10 7/8 in.); Sheet: 26.2 × 40 cm (10 3/8 × 15 3/4 in.)",
      "medium_display": "Drypoint on cream laid paper",
      "credit_line": "Gift of Wallace L. DeWolf",
      "provenance_text": null,
      "artwork_type_title": "Print",
      "artist_id": 24506,
      "artist_title": "Thomas George Soper",
      "term_titles": "[\"drypoint\",\"paper (fiber product)\",\"print\",\"prints and drawing\"]",
      "image_id": "b2c996e3-d3d1-4e9c-dd25-f615a3fd60f4",
      "alt_text": "A work made of drypoint on cream laid paper."
    },
    {
      "id": 114178,
      "title": "Gypsy Caravan on Bridge",
      "date_start": 1840,
      "date_end": 1845,
      "artist_display": "William James Muller (English, 1812-1845)\nor a follower of John Linnell (English, 1792-1882)",
      "place_of_origin": "England",
      "description": null,
      "dimensions": "17.2 × 25.7 cm (6 13/16 × 10 1/8 in.)",
      "medium_display": "Pen and brown ink with brush and watercolor and gouache, over graphite, on gray wove paper, laid down on board",
      "credit_line": "The Leonora Hall Gurley Memorial Collection",
      "provenance_text": null,
      "artwork_type_title": "Drawing and Watercolor",
      "artist_id": 40945,
      "artist_title": "William James Muller",
      "term_titles": "[\"watercolor\",\"paper (fiber product)\",\"ink\",\"watercolor\",\"water-base paint\",\"paint\",\"gouache\",\"graphite\",\"drawings (visual works)\",\"prints and drawing\"]",
      "image_id": "124ca698-69ee-32da-64f0-d75b963d27bf",
      "alt_text": "A work made of pen and brown ink with brush and watercolor and gouache, over graphite, on gray wove paper, laid down on board."
    },
    {
      "id": 116587,
      "title": "Starfighter, from Capitalist Realism",
      "date_start": 1967,
      "date_end": 1967,
      "artist_display": "Wolf Vostell\nGerman, 1932-1998",
      "place_of_origin": "Germany",
      "description": null,
      "dimensions": "53 × 81.5 cm (20 7/8 × 32 1/8 in.)",
      "medium_display": "Screenprint, flocked with glitter on white wove paper",
      "credit_line": "Purchased with funds provided by Mr. and Mrs. Robert O. Delaney",
      "provenance_text": null,
      "artwork_type_title": "Print",
      "artist_id": 42559,
      "artist_title": "Wolf Vostell",
      "term_titles": "[\"screen printing\",\"screenprint\",\"paper (fiber product)\",\"print\",\"prints and drawing\"]",
      "image_id": "072fc0c3-d7e1-4c60-1404-1310ca431a55",
      "alt_text": "A work made of screenprint, flocked with glitter on white wove paper."
    },
    {
      "id": 156297,
      "title": "Sunrise—The Pond, East Hampton",
      "date_start": 1883,
      "date_end": 1883,
      "artist_display": "Thomas Moran\nAmerican, born England, 1837-1926",
      "place_of_origin": "United States",
      "description": null,
      "dimensions": "Image: 11.1 × 17.9 cm (4 3/8 × 7 1/16 in.); Plate: 11.3 × 18.1 cm (4 1/2 × 7 3/16 in.); Sheet: 24 × 31.1 cm (9 1/2 × 12 1/4 in.)",
      "medium_display": "Etching on cream laid paper",
      "credit_line": "Gift of Frederick W. Renshaw",
      "provenance_text": null,
      "artwork_type_title": "Print",
      "artist_id": 35821,
      "artist_title": "Thomas Moran",
      "term_titles": "[\"etching\",\"paper (fiber product)\",\"print\",\"prints and drawing\"]",
      "image_id": "4561920d-c110-897f-9822-db1177227526",
      "alt_text": "A work made of etching on cream laid paper."
    },
    {
      "id": 251188,
      "title": "A distant view at the Tama River (One Hundred Views of Tokyo, Message to the 21st Century 東京百景 21世紀へのメッセジ)",
      "date_start": 1990,
      "date_end": 1990,
      "artist_display": "Horii Hideo (b. 1934-1994)\nJapanese",
      "place_of_origin": "Japan",
      "description": null,
      "dimensions": "68 × 50 cm (27 × 20 in.)",
      "medium_display": "Copper print on paper",
      "credit_line": "Louise A. Lutz Endowment and Asian Art Council Acquisition funds",
      "provenance_text": null,
      "artwork_type_title": "Print",
      "artist_id": 11519,
      "artist_title": "Horii Hideo",
      "term_titles": "[]",
      "image_id": "1466ba88-0b34-30bf-25ad-0bfddfc7ef0f",
      "alt_text": "A work made of copper print on paper."
    },
    {
      "id": 251250,
      "title": "Nocturene - The Sumida River (One Hundred Views of Tokyo, Message to the 21st Century 東京百景 21世紀へのメッセジ)",
      "date_start": 1989,
      "date_end": 1999,
      "artist_display": "Furutani Hiroko\nJapanese",
      "place_of_origin": "Japan",
      "description": null,
      "dimensions": "68 × 50 cm (27 × 20 in.)",
      "medium_display": null,
      "credit_line": "Louise A. Lutz Endowment and Asian Art Council Acquisition funds",
      "provenance_text": null,
      "artwork_type_title": "Print",
      "artist_id": 116770,
      "artist_title": "Furutani Hiroko",
      "term_titles": "[]",
      "image_id": "b8324319-6237-272c-3ec3-c5be155f98b9",
      "alt_text": "A work."
    },
    {
      "id": 105101,
      "title": "First View of the Yosemite Valley from the Mariposa Trail",
      "date_start": 1865,
      "date_end": 1866,
      "artist_display": "Carleton E. Watkins\nAmerican, 1829-1916",
      "place_of_origin": "United States",
      "description": "<p>In the 1860s, Carleton Watkins was the first to document the untouched wilderness that would become Yosemite National Park. Transporting his fragile equipment on mule or carriage through difficult terrain, Watkins used a &quot;mammoth-plate&quot; camera whose glass negatives measured up to 18 by 22 inches and yielded remarkably detailed prints of the same size. He favored spectacular compositions with dramatic spatial depth. In this photograph, Watkins depicted Yosemite Valley's immense span through the receding planes of mountains and the giant Sequoia trees that frame them. Watkins printed more than 1,100 mammoth-plate photographs over the course of his career. Unfortunately, the majority of his glass negatives and prints were destroyed in the San Francisco earthquake and fire of 1906.</p>\n",
      "dimensions": "Image/paper: 39.9 × 52.4 cm (15 3/4 × 20 11/16 in.); Mount: 47.4 × 61 cm (18 11/16 × 24 1/16 in.)",
      "medium_display": "Albumen print",
      "credit_line": "Laura T. Magnuson and Maurice D. Galleher Endowments",
      "provenance_text": null,
      "artwork_type_title": "Photograph",
      "artist_id": 28036,
      "artist_title": "Carleton Watkins",
      "term_titles": "[\"albumen silver print\",\"traditional landscapes\",\"19th century\",\"photography\",\"photographic process\",\"photography\",\"landscapes\",\"photograph\"]",
      "image_id": "09b6a369-8934-7a4d-0370-90509dde6607",
      "alt_text": "A work made of albumen print."
    },
    {
      "id": 61707,
      "title": "La Caravane du Caire (The Caravan from Cairo) (Furnishing Fabric)",
      "date_start": 1785,
      "date_end": 1805,
      "artist_display": "Manufactured by Petitpierre et Cie. (French c. 1760-1791)\nFrance, Nantes",
      "place_of_origin": "France",
      "description": null,
      "dimensions": "169.8 × 97.7 cm (66 7/8 × 38 1/2 in.)",
      "medium_display": "Cotton, plain weave; copperplate printed",
      "credit_line": "Purchased with funds provided by Martha Borland Willis in memory of Mrs. Chauncey B. Borland",
      "provenance_text": null,
      "artwork_type_title": "Textile",
      "artist_id": 20421,
      "artist_title": "Petitpierre et Cie.",
      "term_titles": "[\"copperplate printing\",\"textile\",\"weaving - printed\",\"furnishing textile\"]",
      "image_id": "af20d1a4-3a98-4bbf-8e6c-4a1719a9b601",
      "alt_text": "A work made of cotton, plain weave; copperplate printed."
    },
    {
      "id": 105432,
      "title": "Caravan (Furnishing Fabric)",
      "date_start": 1962,
      "date_end": 1962,
      "artist_display": "Designed by Anita Askild (American, born Sweden, 1933–1980) and Larsen Design Studio (American, 1958-1997)\nProduced by Jack Lenor Larsen Inc. (American, 1952-1997)\nUnited States, New York, New York",
      "place_of_origin": "New York City",
      "description": null,
      "dimensions": "520.5 × 138.1 cm (205 × 54 3/8 in.)",
      "medium_display": "Cotton, plain weave with supplementary pile warps forming cut, solid velvet; screen printed",
      "credit_line": "Gift of Jack Lenor Larsen",
      "provenance_text": null,
      "artwork_type_title": "Textile",
      "artist_id": 30442,
      "artist_title": "Anita Askild",
      "term_titles": "[\"textile\",\"weaving - printed\",\"furnishing textile\"]",
      "image_id": "5667e1a9-ab58-8678-022b-ea9d0e2555bd",
      "alt_text": "A work made of cotton, plain weave with supplementary pile warps forming cut, solid velvet; screen printed."
    },
    {
      "id": 241667,
      "title": "La Caravane du Caire (The Caravan from Cairo) (Furnishing Fabric)",
      "date_start": 1785,
      "date_end": 1805,
      "artist_display": "Manufactured by Petitpierre et Cie. (French c. 1760-1791)\nFrance, Nantes",
      "place_of_origin": "France",
      "description": null,
      "dimensions": "167.6 × 30.2 cm (66 × 11 7/8 in.)",
      "medium_display": "Cotton, plain weave; copperplate printed",
      "credit_line": "Purchased with funds provided by Martha Borland Willis in memory of Mrs. Chauncey B. Borland",
      "provenance_text": null,
      "artwork_type_title": "Textile",
      "artist_id": 20421,
      "artist_title": "Petitpierre et Cie.",
      "term_titles": "[\"copperplate printing\",\"textile\",\"weaving - printed\",\"furnishing textile\"]",
      "image_id": "4a3e86a1-61db-1e5c-5599-5cd9f432952a",
      "alt_text": "A work made of cotton, plain weave; copperplate printed."
    },
    {
      "id": 210878,
      "title": "Letter to my Friend in Paris (Levél barátomnak Párizsba)",
      "date_start": 1975,
      "date_end": 1975,
      "artist_display": "Tibor Hajas\nHungarian, 1946–1980",
      "place_of_origin": "Hungary",
      "description": null,
      "dimensions": "Each: 17.6 × 23.8 cm (6 15/16 × 9 3/8 in.)",
      "medium_display": "Gelatin silver prints (7)",
      "credit_line": "Photography Gala Fund",
      "provenance_text": null,
      "artwork_type_title": "Photograph",
      "artist_id": 111746,
      "artist_title": "Tibor Hajas",
      "term_titles": "[\"photograph\",\"Paris\",\"black-and-white photography\",\"photography\",\"photographic processes\",\"photographic techniques\",\"photography\"]",
      "image_id": "60544248-67b7-5e7b-ffcf-52b35cf3cd0c",
      "alt_text": "A work made of gelatin silver prints (7)."
    }
  ]);
};
